teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.2
    scale_linear_turbo:
      x: 0.5
    
    axis_linear:  # Left thumb stick vertical
      y: 0
    scale_linear:
      y: -0.2
    scale_linear_turbo:
      y: -0.5

    axis_angular:  # Left thumb stick horizontal
      yaw: 3
    scale_angular:
      yaw: -0.05

    enable_button: 4  # Left trigger button
    enable_turbo_button: 5  # Right trigger button
